version: '3.8'

services:
  # LibreOffice Online (Collabora)
  libreoffice:
    image: libreoffice/online
    container_name: libreoffice-online
    ports:
      - "9980:9980"
    environment:
      - "domain=localhost"  # Remplacez par votre domaine si en production
      - "username=admin"    # Optionnel : utilisateur admin
      - "password=secret"   # Optionnel : mot de passe admin
    cap_add:
      - MKNOD
    restart: unless-stopped

  # Serveur Node.js pour l'interface d'upload
  # node-app:
  #   build: ./node-app
  #   container_name: node-app
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./node-app:/app
  #     - ./node-app/uploads:/app/uploads  # Stockage des fichiers uploadés
  #   depends_on:
  #     - libreoffice
  #   restart: unless-stopped

  # # Nginx (optionnel - pour HTTPS et reverse proxy)
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"  # Si vous avez HTTPS
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./node-app:/var/www/html  # Servir les fichiers statiques
  #     - ./certbot/conf:/etc/letsencrypt  # Si HTTPS (Let's Encrypt)
  #   depends_on:
  #     - node-app
  #   restart: unless-stopped